title: Prison Books Collective
general_email: prisonbooks@gmail.com
mailing_address: PO Box 625, Carrboro, NC 27510
patron_signup: https://docs.google.com/forms/d/e/1FAIpQLScfBxeuPKoxnt70nVhsjHD0dbvmr8whO3ILP7JBVX3JO5CqOQ/viewform?usp=sf_link
description: A Durham-based all-volunteer nonprofit sending books and resources to imprisoned people in North Carolina and Alabama.
baseurl: 
url: "http://prisonbooks.info" # the base hostname & protocol for your site

twitter_link: https://www.twitter.com/NCPrisonBooks
instagram_link: https://www.instagram.com/prisonbookscollective
facebook_link: https://www.facebook.com/prisonbookscollective

flyleaf_wishlist: https://flyleafbooks.com/wishlist/swacredrowrud
goldenFig_wishlist: https://www.goldenfigbooks.com/wishlist/230
quailRidge_wishlist: https://www.quailridgebooks.com/wishlist/1863
amazon_wishlist: https://www.amazon.com/gp/registry/wishlist/RMMK6YRO4PXV

zine_catalog: /img/resource-zine-catalog-2023.pdf
resource_guide: /img/resource-resource-guide-2021.pdf



# Build settings
sass:
  sass_dir: /styles/sass
markdown: kramdown
